# Generated by Django 3.0.4 on 2020-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('Apaterno', models.CharField(max_length=20)),
                ('Amaterno', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
